version: "3.0"

services:
  api:
    build: ./api
    container_name: docker-api-template
    restart: always
    networks:
      - proxy_net
      - core_net
    ports:
      - "3102:3102"

  app:
    build: ./app
    container_name: docker-app-template
    restart: always
    networks:
      - proxy_net
    ports:
      - "3201:80"

networks:
  core_net:
    external: true
  proxy_net:
    external: true