services:
  api:
    build: ./api
    networks:
      - proxy_net
      - core_net
    expose:
      - "3102"

  app:
    build: ./app
    networks:
      - proxy_net
    expose:
      - "80"

networks:
  proxy_net:
    external: true
  core_net:
    external: true
