services:
  api:
    build: ./api
    container_name: dev-docker-api-template
    networks:
      - proxy_net
      - core_net
    expose:
      - "3102"

  app:
    build: ./app
    container_name: dev-docker-app-template
    networks:
      - proxy_net
    expose:
      - "80"

networks:
  proxy_net:
    external: true
  core_net:
    external: true
