services:
  api:
    build: ./api
    container_name: dev-docker-api-template
    networks:
      - proxy_net
      - core_net
    ports:
      - "3112:3112"

  app:
    build: ./app
    container_name: dev-docker-app-template
    networks:
      - proxy_net
    ports:
      - "3211:80"

networks:
  proxy_net:
    external: true
  core_net:
    external: true
