name: ğŸš€ Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¤ Copy private key to VPS (debug only)
        run: |
          scp -o StrictHostKeyChecking=no private_key.pem ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/tmp/private_key.pem

      - name: ğŸ§° Checkout code
        uses: actions/checkout@v4

      - name: ğŸ” Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: ğŸš€ Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            cd ${{ secrets.VPS_PATH }} &&
            git pull &&
            docker compose build &&
            docker compose up -d
          "
