name: ğŸš€ Deploy to VPS

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§° Checkout code
        uses: actions/checkout@v4

      - name: ğŸ” Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: ğŸš€ Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            set -e
            cd ${{ secrets.VPS_PATH }}

            if [ '${{ github.ref_name }}' = 'master' ]; then
              echo 'Deploying PRODUCTION'
              git fetch origin master
              git reset --hard origin/master
              docker compose down
              docker compose up -d --build

            elif [ '${{ github.ref_name }}' = 'dev' ]; then
              echo 'Deploying DEVELOPMENT'
              git fetch origin dev
              git reset --hard origin/dev
              docker compose -f docker-compose.dev.yml down
              docker compose -f docker-compose.dev.yml up -d --build
            fi
          "
