name: ðŸš€ Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Deploy
        run: |
          ssh deploy@${{ secrets.VPS_HOST }} << 'EOF'
            cd /srv/apps/project
            git fetch origin

            if [ "${{ github.ref_name }}" = "master" ]; then
              git checkout master
              git pull
              docker compose up -d --build

            elif [ "${{ github.ref_name }}" = "dev" ]; then
              git checkout dev
              git pull
              docker compose -f docker-compose.dev.yml up -d --build

            else
              echo "Feature branch deploy skipped"
            fi
          EOF
